### ISSUE TITLE
Question about field monitor

### ISSUE THREAD

**Issue by jschenke488** [Filip-Kin/FTA-Buddy#1]
I found this app when I was re-downloading the original FTA Buddy, and thank you for all the updates! Me and Ken would like to use this app at the regionals here in Kansas City, but I don't think we'll be able to run a server on the network. Does the field monitor still work without the server, and if not could an option to use the original field monitor tab be added?

**Comment by jschenke488** [comment]
If you want to create a PR on Ken's repo, we can merge the changes back into the original project.

**Comment by Filip-Kin** [comment]
I like the idea, if I'll implement it when I work on it next. This repo is actually not a fork of the original project because I rewrote it from the ground up.
I might also make an option to have the browser extension send data to the cloud immediately. 
I don't do any events outside of FIM, are they more restrictive on what you can put on the field network at regionals?

**Comment by jschenke488** [comment]
Would transferring ownership to Ken and adding you as a contributor work? I'll add a page with credits since I've already created a settings page for this feature. I don't know the details myself about restrictions on the field network, but we just don't have an extra computer laying around we can use.
![studio64_VG01H332Ey](https://github.com/Filip-Kin/FTA-Buddy/assets/44783760/c8346762-b2ef-4d58-bea1-107c8852b2b2)

**Comment by Filip-Kin** [comment]
You're welcome to develop the feature and make a pull-request against this repository, but I would like to maintain ownership

**Comment by kenschenke** [comment]
I love the extra reference material you have on the Rev stuff.  I would like to back-port it into my app and credit you.

**Comment by Filip-Kin** [comment]
I've made it so you only need the chrome extension now, simpler to setup although requires an internet connection. Usually not a problem at competitions though. Also I've abandoned the android app and made it a progressive web app because it's just easier to develop and works cross platform, [App](https://ftabuddy.com/app/).
